### ISSUE TITLE
Errrrr

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/myst-demo#1]
@rowanc1 I've already just made a myst demonstrator https://executablebooks.github.io/myst-react/ which (in my biased opinion) is basically a better version of this 😬 so we should make sure we are not duplicating effort

**Comment by chrisjsewell** [comment]
I mean I can see how it could be useful, if you want to embed it in some where, but hmmm 🤔

**Comment by rowanc1** [comment]
Yeah - this is a small component to go in docs to have a quick interactive experience. Not a full page app.

**Comment by rowanc1** [comment]
Circling back up on this this morning.

I was aiming to have a very simple component that allows for fiddling/interacting in documentation - which I really think is helpful in a lot of good docs that I have seen around the place (i.e. in-context demos). It is also helping in my testing as I am writing the docs out for `markdown-it-myst`.

I think some of the confusion might have come out of the name of the repo, which is probably good for a web-component `<myst-demo>` but maybe confusing from the repo name, as it gave the impression of overlap with the recent `myst-react` repo. Happy to change the name, and open to suggestions. `myst-demo-web-component` `wc-myst-demo`?

I don't think that there is much overlap in the actual goals of having a super-solid demo page for myst (which this is not), and the scope of this repo is largely complete.
