### ISSUE TITLE
Decode HTML before populating myst demo text area

### ISSUE THREAD

**Issue by fwkoch** [executablebooks/myst-demo#2]
Examples:

![image](https://user-images.githubusercontent.com/9453731/154361259-12822a3b-2f32-4eb9-b91b-642b03595c53.png) 

gives

![image](https://user-images.githubusercontent.com/9453731/154361300-f94adade-bd58-4002-8592-4a8215b59f59.png)

and

![image](https://user-images.githubusercontent.com/9453731/154361018-44f6f899-f7a8-463c-9c7b-e17afc677043.png)

gives

![image](https://user-images.githubusercontent.com/9453731/154361206-61fa1ad0-e33d-4b75-be98-25704b089ea8.png)

**Comment by rowanc1** [comment]
Fixed!
